### ISSUE TITLE
White background 

### ISSUE THREAD

**Issue by astract** [astract/astract.github.io#4]
Sometimes show white background, however hex code correct

**Comment by peter-nikitin** [comment]
Поймал белый фон

Состояние переменных
```css
--color_top: #9fcff;
--color_bottom: #b1816c;
```

color_top - 5 символов, а должно быть 6.

Несколько раз подергал `Math.floor(Math.random() * 16777215)` и получил в итоге `76481` 
Приведение этого числа к 16ричной системе дает `(76481).toString(16) => 12ac1` - а это невалидный цвет 

--

Возможно стоит рассмотреть другой алгоритм генерации цвета.
Цвет в HEX - это 3 числа в диапазоне 0 - 255 переведенные в 16 систему. То есть диапазон допустимых значений для HEX: 000000 - FFFFFF

B отсюда может стоит генерировать 3 рандомных числа, переводить их в 16 и потом их склеивать в строку?
